
### Get nodes
GET http://127.0.0.1:5000/nodeInstances

### Get node type
GET http://127.0.0.1:5000/nodeTypes/round_float

### Get node instance
GET http://127.0.0.1:5000/nodeInstances/2

### Set overwrite_kwarg
PUT http://127.0.0.1:5000/nodeInstances/2/kwargs/digits
Content-Type: text/plain

3


