### Get all node types
GET http://127.0.0.1:5000/nodeTypes

### Get specific node type
GET http://127.0.0.1:5000/nodeTypes/add_int

### Get specific node type
GET http://127.0.0.1:5000/nodeTypes/remove_outliers

### Get all nodes
GET http://127.0.0.1:5000/nodeInstances

### Get specific node
GET http://127.0.0.1:5000/nodeInstances/1

### Get specific nonexistent node
GET http://127.0.0.1:5000/nodeInstances/100

### Get specific link
GET http://127.0.0.1:5000/nodeLinks/1

### Remove a specific link
DELETE http://127.0.0.1:5000/nodeLinks/1

### Remove nonexistant link
DELETE http://127.0.0.1:5000/nodeLinks/10

### Add link between 1 and 3
POST http://127.0.0.1:5000/nodeLinks
Content-Type: application/json

{
    "origin_node_id": 0,
    "origin_node_output": null,
    "destination_node_id": 3,
    "destination_node_input": "a"
}

### Patch added link
PATCH http://127.0.0.1:5000/nodeLinks/3
Content-Type: application/json

{
    "origin_node_id": 0,
    "origin_node_output": null,
    "destination_node_id": 2,
    "destination_node_input": "asfjkl"
}

### Get added link
GET http://127.0.0.1:5000/nodeLinks/3

### Get all node links
GET http://127.0.0.1:5000/nodeLinks

### Get node links with specific origin
GET http://127.0.0.1:5000/nodeLinks?origin_node_id=0

### Get node links with specific destination
GET http://127.0.0.1:5000/nodeLinks?destination_node_id=2

### Get node links with specific origin and  destination
GET http://127.0.0.1:5000/nodeLinks?origin_node_id=2&destination_node_id=3

### Delete node
DELETE http://127.0.0.1:5000/nodeInstances/1

### Add node
POST http://127.0.0.1:5000/nodeInstances
Content-Type: application/json

{
    "node_type": "add_int",
    "position_x": 1,
    "position_y": 1

}

### Get specific node
GET http://127.0.0.1:5000/nodeInstances/0

### Patch specific node instance
PATCH  http://127.0.0.1:5000/nodeInstances/0
Content-Type: application/json

{
    "instance_name": "a1",
    "position_x": 101,
    "position_y": 150

}
